// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifvhmiusfjmtllzkzhzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdmhtaXVzZmptdGxsemt6aHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTk3MjgsImV4cCI6MjA3MTczNTcyOH0.3egxs9ToNW0saQrc_7tlenjHZjQjqT71FCIsN60wMmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});